### ISSUE TITLE
Error for CDKN2C gene

### ISSUE THREAD

**Issue by gmeurice** [pbnjay/lollipops#34]
Dear Jeremy,

I got the following error using lollipops for CDKN2C (HUMAN). But the gene is there : 
http://www.uniprot.org/uniprot/?query=CDKN2C&sort=score

bests,
```
./lollipops CDKN2C      
ERROR: Unable to find Arial.ttf - Which is required for accurate font sizing.
       Please use -f=/path/to/arial.ttf or the TrueType (.ttf) font of your choice.
HGNC Symbol:  CDKN2C
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/pbnjay/lollipops/data.GetProtID(0x7fff5fbfef1c, 0x6, 0x0, 0x0, 0x0, 0x0)
        /Users/jeremy/src/github.com/pbnjay/lollipops/data/fetch_data.go:131 +0xeb2
main.main()
        /Users/jeremy/src/github.com/pbnjay/lollipops/main.go:160 +0x85a

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 23 [IO wait]:
net.runtime_pollWait(0x12b58f8, 0x72, 0xc8200860a0)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820080760, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820080760, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820080700, 0xc8200da000, 0x1000, 0x1000, 0x0, 0x12b0028, 0xc8200860a0)
        /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820096098, 0xc8200da000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x12b59b8, 0xc820096098, 0xc8200d41b8, 0xc8200da000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8200986e0, 0xc8200da000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc820084540)
        /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820084540, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8200d4160)
        /usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 24 [select]:
net/http.(*persistConn).writeLoop(0xc8200d4160)
        /usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:686 +0xc9d
```

**Comment by pbnjay** [comment]
Thanks for reporting this, I wasn't checking bounds there so it shouldn't have crashed like that.

However, it appears that Uniprot does not list "CDKN2C" as a name for any of the search results for "CDKN2C" which is very odd. It appears to be because Uniprot has no PFAM annotation (and that is one of the search filters).

Anyways. Clearly PFAM does have a record, it's just not linked on Uniprot. So if you use `./lollipops -U P42773` instead of the name you should be fine.
